### ISSUE TITLE
Feature request: SET_DHW_SETPOINT service

### ISSUE THREAD

**Issue by anybody84** [mvn23/pyotgw#16]
It would be nice to implement a service for setting up domestic hot water setpoint.
As per OTGW documentation the command is:

> SW=temperature
Setpoint Water - Set the domestic hot water setpoint. This command is only available with boilers that support this function.
Examples: SW=60, SW=+40.0

For more information please refer to this [link](http://otgw.tclcode.com/firmware.html#operation).

**Comment by mvn23** [comment]
This is [already implemented](https://github.com/mvn23/pyotgw/blob/873f05a93e83ddafca8ca49a9de4e6b9c3d92937/pyotgw/pyotgw.py#L710).
