### ISSUE TITLE
Feature request: SET_DWH_ENABLE_OPTION service

### ISSUE THREAD

**Issue by anybody84** [mvn23/pyotgw#18]
It would be nice to implement a service for controlling domestic hot water enable option, cause if you're going on vacation it actually does not make sense to keep the water hot.

As per OTGW documentation the command is:

> HW=state
Hot Water - Control the domestic hot water enable option. If the boiler has been configured to let the room unit control when to keep a small amount of water preheated, this command can influence that. A state of 0 or 1 will tell the boiler whether or not to keep the water warm. Any other single character causes the gateway to let the thermostat control the boiler. Possible values are 0, 1, or any other single character.
Examples: HW=1, HW=T

For more information please refer to this [link](http://otgw.tclcode.com/firmware.html#operation).

**Comment by mvn23** [comment]
This is [already implemented](https://github.com/mvn23/pyotgw/blob/873f05a93e83ddafca8ca49a9de4e6b9c3d92937/pyotgw/pyotgw.py#L387).

If you're requesting an implementation for these functions in Home Assistant, then this is not the right place. Similar requests [have been made before](https://github.com/home-assistant/core/issues/24632), but it does not have priority for me.
