### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fabaff** [mvn23/pyotgw#33]
It would be nice if there would be a new release that include the tests.

Thanks

**Comment by mvn23** [comment]
This is planned for v2.0 at the moment.
I have been working on a rewrite of most of the code over the last weeks (months?). Unfortunately I have been quite busy with other things recently, so the work on this got interrupted.

Is this the only thing blocking nixpkgs integration right now? In that case I may consider releasing another 1.x with tests included before v2.0 comes along.
