### ISSUE TITLE
Command PR with value D raised exception: Bad Value:

### ISSUE THREAD

**Issue by DJTerentjev** [mvn23/pyotgw#34]
Hello, not an issue, just a question. 
I am using OTGW integration for long time. It's work great! Only every start-up of HA I got error: 
Command PR with value D raised exception: Bad Value: The command contained a data value that is not allowed or not supported on this version of the OpenTherm Gateway.

As I understand it some command from boiler:  Print Report: The DS18x20 temperature sensor function. Which not suported by OTWG.

Is something I can do to get rid of this error?

Thank you!

**Comment by mvn23** [comment]
Thank you for the report. This may indeed be a bug in pyotgw. `PR=D` was added in Opentherm Gateway 5.0 and the error should be silently ignored if your version is lower than that.

Can you confirm your Opentherm Gateway firmware version?

**Comment by DJTerentjev** [comment]
I think it was 4.2.4.

**Comment by mvn23** [comment]
If you enable entity `sensor.otgw_about_gateway_*` (* = your gateway ID) it will show you the version.

**Comment by DJTerentjev** [comment]
OpenTherm Gateway 4.2.5

**Comment by mvn23** [comment]
Thanks, will be fixed in v2.0.

**Comment by DJTerentjev** [comment]
Thank you! 
One more question if you don't mind.
Please see below. All entities related to boiler errors have unavailable state.  I older version of integration I had them showing states. And once I catched error of the boiler one. It is because errors inactive at the moment? 
![OTGW](https://user-images.githubusercontent.com/1267473/134435229-8d2a57b7-c732-4c21-a19f-17e74f632b4d.jpg)

**Comment by mvn23** [comment]
If the sensor is marked as "unavailable" it means that the Opentherm Gateway did not (yet) supply any useful information on that particular parameter, i.e. the state is unknown.

**Comment by DJTerentjev** [comment]
Got it. Thank you!

**Comment by andriej** [comment]
I was about to post same issue but thought it's my installation fault. 

Is it worth upgrading to 5.0? :-)
