### ISSUE TITLE
Command PR failed

### ISSUE THREAD

**Issue by akula3** [mvn23/pyotgw#52]
I'm getting a lot of warnings like this:
```
Logger: pyotgw.commandprocessor
Source: runner.py:120
First occurred: 1. Februar 2023 um 16:31:28 (260490 occurrences)
Last logged: 05:26:04

Command PR failed with PR: Q=P, retrying...
Unknown message in command queue: PR: S=16.00
Command PR failed with PR: S=16.00, retrying...
Received Error 03. If this happens during a reset of the gateway it can be safely ignored.
Command PR failed with Error 03, retrying...
```
How can I prevent that?

**Comment by mvn23** [comment]
As I wrote on the HA issue as well:
If you're trying to connect more than one thing to the gateway things like this will happen.
However, `Error 03` is an error that is generated by the gateway itself (see [here](https://otgw.tclcode.com/firmware.html#errors)) If you see a lot of these (I sure hope there aren't 260490 in your logs), please have a look at the troubleshooting section of the [OpenTherm Gateway docs](https://otgw.tclcode.com/debugging.html#slave).
