### ISSUE TITLE
Missing opentherm_gw.set_target_temp (and others) in HA integration

### ISSUE THREAD

**Issue by blb4github** [mvn23/pyotgw#89]
Hi,

It looks like not all set options from the list in pyotgw are available in the Home Assistant integration, One I'm missing is set_target_temp. Would it be possible to get that one into the HA integration? Maybe this is not an issue for pyotgw but for HA Core, should I place it there?

**Comment by mvn23** [comment]
You can control the target temperature with the `climate` entity and its related `climate` service actions. What would be the use case for `set_target_temp` as a separate service action?
If you have a use case that is not yet covered by Home Assistant but is supported in `pyotgw` then the correct place would indeed be the HA core issue tracker.

**Comment by blb4github** [comment]
Thanks, the answer for asking for this is I don't see the climate entity working. I'll have a further look at that first. Anyhow, this is then indeed more HA related then pyotgw.
