### ISSUE TITLE
[HA] OpenTherm integration (UI)

### ISSUE THREAD

**Issue by andriej** [mvn23/pyotgw#9]
Would it be possible to implement OpenTherm Gateway integration in Home Assistant as an "config flow" one?
I'm already happy with it - but additional possibilities hidden behind entity register, disabling those which are not used (supported by boiler) would be even better.

Just a thing to consider - as I can see OT is already very integrated inside HA anyway, hope it's not much of a hassle to make integration via UI possible.

**Comment by andriej** [comment]
Looking more into the issue - to be able to turn off entities in HA they only need to have unique id set by integration. So even (less) hassle getting it to work and so much easier life with possibility of turning unwanted ones off forever.

**Comment by mvn23** [comment]
Closing this as it is not a pyotgw issue.
Either way, I am planning to do this in the future.
